{
	"document_title": "Security update for python-Django",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2025:0149-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2025-01-16T17:03:39Z",
				"description": "current"
			}
		},
		"initial_release_date": "2025-01-16T17:03:39Z",
		"current_release_date": "2025-01-16T17:03:39Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Django",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Django fixes the following issues:\n\n- CVE-2024-56374: Fixed lack of upper bound limit enforcement in strings when performing IPv6 validation that could lead to denial of service (bsc#1235856)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2025-149,SUSE-SLE-Module-Packagehub-Subpackages-15-SP6-2025-149,openSUSE-SLE-15.6-2025-149",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2025/suse-su-20250149-1/",
			"description": "Link for SUSE-SU-2025:0149-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2025-January/020149.html",
			"description": "E-Mail link for SUSE-SU-2025:0149-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1235856",
			"description": "SUSE Bug 1235856"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-56374/",
			"description": "SUSE CVE CVE-2024-56374 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
							"product_id": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
							"cpe": "cpe:/o:suse:packagehub:15:sp6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.6",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.6",
						"full_product_name": {
							"text": "openSUSE Leap 15.6",
							"product_id": "openSUSE Leap 15.6",
							"cpe": "cpe:/o:opensuse:leap:15.6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python311-Django-4.2.11-150600.3.15.1",
				"full_product_name": {
					"text": "python311-Django-4.2.11-150600.3.15.1",
					"product_id": "python311-Django-4.2.11-150600.3.15.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python311-Django-4.2.11-150600.3.15.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Package Hub 15 SP6"
			},
			{
				"product_reference": "python311-Django-4.2.11-150600.3.15.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when performing IPv6 validation could lead to a potential denial-of-service attack. The undocumented and private functions clean_ipv6_address and is_valid_ipv6_address are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField model field is not affected.)",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-56374",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.15.1",
						"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.15.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2025/suse-su-20250149-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-56374.html",
					"description": "CVE-2024-56374"
				},
				{
					"url": "https://bugzilla.suse.com/1235856",
					"description": "SUSE Bug 1235856"
				}
			]
		}
	]
}
