{
	"document_title": "Security update for python-Django",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2015:1810-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2015-10-15T02:38:16Z",
				"description": "current"
			}
		},
		"initial_release_date": "2015-10-15T02:38:16Z",
		"current_release_date": "2015-10-15T02:38:16Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Django",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "\nThis update for python-Django fixes the following security issues:\n\n- Prevent Denial-of-service possibility by filling session store. (bsc#937522, CVE-2015-5143)\n- Prevent Header injection possibility. (bsc#937523, CVE-2015-5144)\n- A remote denial of service (resource exhaustion) attack against the django session store\n  was fixed in Python Django.  This might have allowed remote attackers to exhaust existing\n  web sessions. (bsc#941587, CVE-2015-5963)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "sleclo50sp3-python-Django-12162",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151810-1/",
			"description": "Link for SUSE-SU-2015:1810-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-October/001643.html",
			"description": "E-Mail link for SUSE-SU-2015:1810-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/937522",
			"description": "SUSE Bug 937522"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/937523",
			"description": "SUSE Bug 937523"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/941587",
			"description": "SUSE Bug 941587"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2015-5143/",
			"description": "SUSE CVE CVE-2015-5143 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2015-5144/",
			"description": "SUSE CVE CVE-2015-5144 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2015-5963/",
			"description": "SUSE CVE CVE-2015-5963 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 5",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 5",
							"product_id": "SUSE OpenStack Cloud 5",
							"cpe": "cpe:/o:suse:cloud:5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-10.2",
				"full_product_name": {
					"text": "python-Django-1.6.11-10.2",
					"product_id": "python-Django-1.6.11-10.2"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Django-1.6.11-10.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The session backends in Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (session store consumption) via multiple requests with unique session keys.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2015-5143",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE OpenStack Cloud 5:python-Django-1.6.11-10.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.8",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:C"
				},
				"score_set_v_3": {},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151810-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2015-5143.html",
					"description": "CVE-2015-5143"
				},
				{
					"url": "https://bugzilla.suse.com/937522",
					"description": "SUSE Bug 937522"
				}
			]
		},
		{
			"notes": [
				{
					"text": "Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2015-5144",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE OpenStack Cloud 5:python-Django-1.6.11-10.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151810-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2015-5144.html",
					"description": "CVE-2015-5144"
				},
				{
					"url": "https://bugzilla.suse.com/937523",
					"description": "SUSE Bug 937523"
				}
			]
		},
		{
			"notes": [
				{
					"text": "contrib.sessions.middleware.SessionMiddleware in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to contrib.auth.views.logout, which triggers the creation of an empty session record.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2015-5963",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE OpenStack Cloud 5:python-Django-1.6.11-10.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151810-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2015-5963.html",
					"description": "CVE-2015-5963"
				},
				{
					"url": "https://bugzilla.suse.com/941587",
					"description": "SUSE Bug 941587"
				}
			]
		}
	]
}
