{
	"document_title": "Security update for python-pyOpenSSL",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2024:3749-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-10-23T15:32:52Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-10-23T15:32:52Z",
		"current_release_date": "2024-10-23T15:32:52Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-pyOpenSSL",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-pyOpenSSL fixes the following issues:\n\n- Fixed error caused by a regression in fix for CVE-2018-1000807 (bsc#1231700)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2024-3749,SUSE-SLE-SAP-12-SP5-2024-3749,SUSE-SLE-SERVER-12-SP5-LTSS-2024-3749,SUSE-SLE-SERVER-12-SP5-LTSS-EXTENDED-SECURITY-2024-3749",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20243749-1/",
			"description": "Link for SUSE-SU-2024:3749-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-October/019671.html",
			"description": "E-Mail link for SUSE-SU-2024:3749-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1231700",
			"description": "SUSE Bug 1231700"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2018-1000807/",
			"description": "SUSE CVE CVE-2018-1000807 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security",
							"product_id": "SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server 12 SP5-LTSS",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server 12 SP5-LTSS",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server 12 SP5-LTSS",
							"product_id": "SUSE Linux Enterprise Server 12 SP5-LTSS",
							"cpe": "cpe:/o:suse:sles-ltss-extended-security:12:sp5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
							"product_id": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
							"cpe": "cpe:/o:suse:sles_sap:12:sp5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-pyOpenSSL-17.1.0-4.29.1",
				"full_product_name": {
					"text": "python-pyOpenSSL-17.1.0-4.29.1",
					"product_id": "python-pyOpenSSL-17.1.0-4.29.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-pyOpenSSL-doc-17.1.0-4.29.1",
				"full_product_name": {
					"text": "python-pyOpenSSL-doc-17.1.0-4.29.1",
					"product_id": "python-pyOpenSSL-doc-17.1.0-4.29.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-pyOpenSSL-17.1.0-4.29.1",
				"full_product_name": {
					"text": "python3-pyOpenSSL-17.1.0-4.29.1",
					"product_id": "python3-pyOpenSSL-17.1.0-4.29.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-pyOpenSSL-17.1.0-4.29.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security"
			},
			{
				"product_reference": "python3-pyOpenSSL-17.1.0-4.29.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security"
			},
			{
				"product_reference": "python-pyOpenSSL-17.1.0-4.29.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 12 SP5-LTSS"
			},
			{
				"product_reference": "python3-pyOpenSSL-17.1.0-4.29.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 12 SP5-LTSS"
			},
			{
				"product_reference": "python-pyOpenSSL-17.1.0-4.29.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server for SAP Applications 12 SP5"
			},
			{
				"product_reference": "python3-pyOpenSSL-17.1.0-4.29.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server for SAP Applications 12 SP5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Python Cryptographic Authority pyopenssl version prior to version 17.5.0 contains a CWE-416: Use After Free vulnerability in X509 object handling that can result in Use after free can lead to possible denial of service or remote code execution.. This attack appear to be exploitable via Depends on the calling application and if it retains a reference to the memory.. This vulnerability appears to have been fixed in 17.5.0.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2018-1000807",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security:python-pyOpenSSL-17.1.0-4.29.1",
						"SUSE Linux Enterprise Server 12 SP5 LTSS Extended Security:python3-pyOpenSSL-17.1.0-4.29.1",
						"SUSE Linux Enterprise Server 12 SP5-LTSS:python-pyOpenSSL-17.1.0-4.29.1",
						"SUSE Linux Enterprise Server 12 SP5-LTSS:python3-pyOpenSSL-17.1.0-4.29.1",
						"SUSE Linux Enterprise Server for SAP Applications 12 SP5:python-pyOpenSSL-17.1.0-4.29.1",
						"SUSE Linux Enterprise Server for SAP Applications 12 SP5:python3-pyOpenSSL-17.1.0-4.29.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "6.8",
					"vector_v_2": "AV:N/AC:M/Au:N/C:P/I:P/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "8.1",
					"vector_v_3": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20243749-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2018-1000807.html",
					"description": "CVE-2018-1000807"
				},
				{
					"url": "https://bugzilla.suse.com/1111634",
					"description": "SUSE Bug 1111634"
				},
				{
					"url": "https://bugzilla.suse.com/1111635",
					"description": "SUSE Bug 1111635"
				}
			]
		}
	]
}
