{
	"document_title": "Security update for python-aiohttp",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2021:1313-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-04-26T07:12:15Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-04-26T07:12:15Z",
		"current_release_date": "2021-04-26T07:12:15Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-aiohttp",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-aiohttp fixes the following issues:\n\n- CVE-2021-21330: Fixed the way pure-Python HTTP parser interprets `//` (bsc#1184745)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2021-1313,SUSE-SLE-Module-Public-Cloud-15-SP1-2021-1313,SUSE-SLE-Module-Public-Cloud-15-SP2-2021-1313,SUSE-SLE-Module-Public-Cloud-15-SP3-2021-1313",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2021/suse-su-20211313-1/",
			"description": "Link for SUSE-SU-2021:1313-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2021-April/008677.html",
			"description": "E-Mail link for SUSE-SU-2021:1313-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1184745",
			"description": "SUSE Bug 1184745"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-21330/",
			"description": "SUSE CVE CVE-2021-21330 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Module for Public Cloud 15 SP1",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Module for Public Cloud 15 SP1",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Module for Public Cloud 15 SP1",
							"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP1",
							"cpe": "cpe:/o:suse:sle-module-public-cloud:15:sp1"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Module for Public Cloud 15 SP2",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Module for Public Cloud 15 SP2",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Module for Public Cloud 15 SP2",
							"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP2",
							"cpe": "cpe:/o:suse:sle-module-public-cloud:15:sp2"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-aiohttp-doc-3.4.4-3.6.1",
				"full_product_name": {
					"text": "python-aiohttp-doc-3.4.4-3.6.1",
					"product_id": "python-aiohttp-doc-3.4.4-3.6.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-aiohttp-3.4.4-3.6.1",
				"full_product_name": {
					"text": "python3-aiohttp-3.4.4-3.6.1",
					"product_id": "python3-aiohttp-3.4.4-3.6.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-aiohttp-doc-3.4.4-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP1"
			},
			{
				"product_reference": "python3-aiohttp-3.4.4-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP1"
			},
			{
				"product_reference": "python-aiohttp-doc-3.4.4-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP2"
			},
			{
				"product_reference": "python3-aiohttp-3.4.4-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP2"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. In aiohttp before version 3.7.4 there is an open redirect vulnerability. A maliciously crafted link to an aiohttp-based web-server could redirect the browser to a different website. It is caused by a bug in the `aiohttp.web_middlewares.normalize_path_middleware` middleware. This security problem has been fixed in 3.7.4. Upgrade your dependency using pip as follows \"pip install aiohttp >= 3.7.4\". If upgrading is not an option for you, a workaround can be to avoid using `aiohttp.web_middlewares.normalize_path_middleware` in your applications.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-21330",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Module for Public Cloud 15 SP1:python-aiohttp-doc-3.4.4-3.6.1",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP1:python3-aiohttp-3.4.4-3.6.1",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP2:python-aiohttp-doc-3.4.4-3.6.1",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP2:python3-aiohttp-3.4.4-3.6.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5.8",
					"vector_v_2": "AV:N/AC:M/Au:N/C:P/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "8.2",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2021/suse-su-20211313-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-21330.html",
					"description": "CVE-2021-21330"
				},
				{
					"url": "https://bugzilla.suse.com/1184745",
					"description": "SUSE Bug 1184745"
				}
			]
		}
	]
}
