{
	"document_title": "Security update for python-Django",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2018:1830-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2018-06-27T13:35:42Z",
				"description": "current"
			}
		},
		"initial_release_date": "2018-06-27T13:35:42Z",
		"current_release_date": "2018-06-27T13:35:42Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Django",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Django fixes the following security issues:\n\n- CVE-2016-2512: The utils.http.is_safe_url function allowed remote attackers\n  to redirect users to arbitrary web sites and conduct phishing attacks or\n  possibly conduct cross-site scripting (XSS) attacks via a URL containing basic\n  authentication (bsc#967999).\n- CVE-2018-7536: The django.utils.html.urlize() function was extremely slow to\n  evaluate certain inputs due to catastrophic backtracking vulnerabilities\n  (bsc#1083304).\n- CVE-2018-7537: If django.utils.text.Truncator's chars() and words() methods\n  were passed the html=True argument, they were extremely slow to evaluate\n  certain inputs due to a catastrophic backtracking vulnerability in a regular\n  expression (bsc#1083305).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-Storage-5-2018-1237",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2018/suse-su-20181830-1/",
			"description": "Link for SUSE-SU-2018:1830-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004226.html",
			"description": "E-Mail link for SUSE-SU-2018:1830-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1083304",
			"description": "SUSE Bug 1083304"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1083305",
			"description": "SUSE Bug 1083305"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/967999",
			"description": "SUSE Bug 967999"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2016-2512/",
			"description": "SUSE CVE CVE-2016-2512 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2018-7536/",
			"description": "SUSE CVE CVE-2018-7536 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2018-7537/",
			"description": "SUSE CVE CVE-2018-7537 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Enterprise Storage 5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Enterprise Storage 5",
						"full_product_name": {
							"text": "SUSE Enterprise Storage 5",
							"product_id": "SUSE Enterprise Storage 5",
							"cpe": "cpe:/o:suse:ses:5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-6.5.1",
				"full_product_name": {
					"text": "python-Django-1.6.11-6.5.1",
					"product_id": "python-Django-1.6.11-6.5.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Django-1.6.11-6.5.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Enterprise Storage 5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2016-2512",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.4",
					"vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2018/suse-su-20181830-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2016-2512.html",
					"description": "CVE-2016-2512"
				},
				{
					"url": "https://bugzilla.suse.com/967999",
					"description": "SUSE Bug 967999"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 2.0 before 2.0.3, 1.11 before 1.11.11, and 1.8 before 1.8.19. The django.utils.html.urlize() function was extremely slow to evaluate certain inputs due to catastrophic backtracking vulnerabilities in two regular expressions (only one regular expression for Django 1.8.x). The urlize() function is used to implement the urlize and urlizetrunc template filters, which were thus vulnerable.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2018-7536",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.3",
					"vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2018/suse-su-20181830-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2018-7536.html",
					"description": "CVE-2018-7536"
				},
				{
					"url": "https://bugzilla.suse.com/1083304",
					"description": "SUSE Bug 1083304"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 2.0 before 2.0.3, 1.11 before 1.11.11, and 1.8 before 1.8.19. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2018-7537",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.3",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2018/suse-su-20181830-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2018-7537.html",
					"description": "CVE-2018-7537"
				},
				{
					"url": "https://bugzilla.suse.com/1083305",
					"description": "SUSE Bug 1083305"
				}
			]
		}
	]
}
