{
	"document_title": "Security update for python-PyJWT",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2022:3545-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2022-10-06T15:03:23Z",
				"description": "current"
			}
		},
		"initial_release_date": "2022-10-06T15:03:23Z",
		"current_release_date": "2022-10-06T15:03:23Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-PyJWT",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-PyJWT fixes the following issues:\n\n- CVE-2022-29217: Fixed key confusion through non-blocklisted public key formats (bsc#1199756).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2022-3545,SUSE-SLE-Module-Public-Cloud-15-2022-3545",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20223545-1/",
			"description": "Link for SUSE-SU-2022:3545-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-October/012512.html",
			"description": "E-Mail link for SUSE-SU-2022:3545-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1199756",
			"description": "SUSE Bug 1199756"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2022-29217/",
			"description": "SUSE CVE CVE-2022-29217 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Module for Public Cloud 15",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Module for Public Cloud 15",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Module for Public Cloud 15",
							"product_id": "SUSE Linux Enterprise Module for Public Cloud 15",
							"cpe": "cpe:/o:suse:sle-module-public-cloud:15"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python2-PyJWT-1.5.3-150000.3.3.1",
				"full_product_name": {
					"text": "python2-PyJWT-1.5.3-150000.3.3.1",
					"product_id": "python2-PyJWT-1.5.3-150000.3.3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-PyJWT-1.5.3-150000.3.3.1",
				"full_product_name": {
					"text": "python3-PyJWT-1.5.3-150000.3.3.1",
					"product_id": "python3-PyJWT-1.5.3-150000.3.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python3-PyJWT-1.5.3-150000.3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "PyJWT is a Python implementation of RFC 7519. PyJWT supports multiple different JWT signing algorithms. With JWT, an attacker submitting the JWT token can choose the used signing algorithm. The PyJWT library requires that the application chooses what algorithms are supported. The application can specify `jwt.algorithms.get_default_algorithms()` to get support for all algorithms, or specify a single algorithm. The issue is not that big as `algorithms=jwt.algorithms.get_default_algorithms()` has to be used. Users should upgrade to v2.4.0 to receive a patch for this issue. As a workaround, always be explicit with the algorithms that are accepted and expected when decoding.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2022-29217",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Module for Public Cloud 15:python3-PyJWT-1.5.3-150000.3.3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20223545-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2022-29217.html",
					"description": "CVE-2022-29217"
				},
				{
					"url": "https://bugzilla.suse.com/1199756",
					"description": "SUSE Bug 1199756"
				},
				{
					"url": "https://bugzilla.suse.com/1223417",
					"description": "SUSE Bug 1223417"
				},
				{
					"url": "https://bugzilla.suse.com/1226138",
					"description": "SUSE Bug 1226138"
				}
			]
		}
	]
}
