{
	"document_title": "Security update for python-numpy",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2022:0118-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2022-01-18T15:41:40Z",
				"description": "current"
			}
		},
		"initial_release_date": "2022-01-18T15:41:40Z",
		"current_release_date": "2022-01-18T15:41:40Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-numpy",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-numpy fixes the following issues:\n\n- CVE-2021-33430: Fixed buffer overflow that could lead to DoS in PyArray_NewFromDescr_int function of ctors.c (bsc#1193913).\n- CVE-2021-41496: Fixed buffer overflow that could lead to DoS in array_from_pyobj function of fortranobject.c (bsc#1193907).  \n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2022-118,SUSE-SLE-SDK-12-SP5-2022-118,SUSE-SLE-SERVER-12-SP5-2022-118",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20220118-1/",
			"description": "Link for SUSE-SU-2022:0118-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010024.html",
			"description": "E-Mail link for SUSE-SU-2022:0118-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1193907",
			"description": "SUSE Bug 1193907"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1193913",
			"description": "SUSE Bug 1193913"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-33430/",
			"description": "SUSE CVE CVE-2021-33430 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-41496/",
			"description": "SUSE CVE CVE-2021-41496 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server 12 SP5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server 12 SP5",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server 12 SP5",
							"product_id": "SUSE Linux Enterprise Server 12 SP5",
							"cpe": "cpe:/o:suse:sles:12:sp5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
							"product_id": "SUSE Linux Enterprise Server for SAP Applications 12 SP5",
							"cpe": "cpe:/o:suse:sles_sap:12:sp5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Software Development Kit 12 SP5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Software Development Kit 12 SP5",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Software Development Kit 12 SP5",
							"product_id": "SUSE Linux Enterprise Software Development Kit 12 SP5",
							"cpe": "cpe:/o:suse:sle-sdk:12:sp5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-numpy-1.8.0-5.11.1",
				"full_product_name": {
					"text": "python-numpy-1.8.0-5.11.1",
					"product_id": "python-numpy-1.8.0-5.11.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-numpy-devel-1.8.0-5.11.1",
				"full_product_name": {
					"text": "python-numpy-devel-1.8.0-5.11.1",
					"product_id": "python-numpy-devel-1.8.0-5.11.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-numpy-doc-html-1.8.0-5.11.1",
				"full_product_name": {
					"text": "python-numpy-doc-html-1.8.0-5.11.1",
					"product_id": "python-numpy-doc-html-1.8.0-5.11.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-numpy-1.8.0-5.11.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 12 SP5"
			},
			{
				"product_reference": "python-numpy-1.8.0-5.11.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server for SAP Applications 12 SP5"
			},
			{
				"product_reference": "python-numpy-devel-1.8.0-5.11.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Software Development Kit 12 SP5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "** DISPUTED ** A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-33430",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Server 12 SP5:python-numpy-1.8.0-5.11.1",
						"SUSE Linux Enterprise Server for SAP Applications 12 SP5:python-numpy-1.8.0-5.11.1",
						"SUSE Linux Enterprise Software Development Kit 12 SP5:python-numpy-devel-1.8.0-5.11.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "3.5",
					"vector_v_2": "AV:N/AC:M/Au:S/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20220118-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-33430.html",
					"description": "CVE-2021-33430"
				},
				{
					"url": "https://bugzilla.suse.com/1193913",
					"description": "SUSE Bug 1193913"
				},
				{
					"url": "https://bugzilla.suse.com/1201968",
					"description": "SUSE Bug 1201968"
				}
			]
		},
		{
			"notes": [
				{
					"text": "** DISPUTED ** Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-41496",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Server 12 SP5:python-numpy-1.8.0-5.11.1",
						"SUSE Linux Enterprise Server for SAP Applications 12 SP5:python-numpy-1.8.0-5.11.1",
						"SUSE Linux Enterprise Software Development Kit 12 SP5:python-numpy-devel-1.8.0-5.11.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "2.1",
					"vector_v_2": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.5",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20220118-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-41496.html",
					"description": "CVE-2021-41496"
				},
				{
					"url": "https://bugzilla.suse.com/1193907",
					"description": "SUSE Bug 1193907"
				}
			]
		}
	]
}
