{
	"document_title": "Security update for python-pip",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2021:2441-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-07-21T11:49:16Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-07-21T11:49:16Z",
		"current_release_date": "2021-07-21T11:49:16Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-pip",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-pip fixes the following issues:\n\n- CVE-2021-3572: Fixed incorrect handling of unicode separators in git references (bsc#1186819).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "HPE-Helion-OpenStack-8-2021-2441,SUSE-2021-2441,SUSE-OpenStack-Cloud-8-2021-2441,SUSE-OpenStack-Cloud-Crowbar-8-2021-2441",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2021/suse-su-20212441-1/",
			"description": "Link for SUSE-SU-2021:2441-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2021-July/009198.html",
			"description": "E-Mail link for SUSE-SU-2021:2441-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1186819",
			"description": "SUSE Bug 1186819"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-3572/",
			"description": "SUSE CVE CVE-2021-3572 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "HPE Helion OpenStack 8",
				"branch": [
					{
						"type": "Product Name",
						"name": "HPE Helion OpenStack 8",
						"full_product_name": {
							"text": "HPE Helion OpenStack 8",
							"product_id": "HPE Helion OpenStack 8",
							"cpe": "cpe:/o:suse:hpe-helion-openstack:8"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 8",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 8",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 8",
							"product_id": "SUSE OpenStack Cloud 8",
							"cpe": "cpe:/o:suse:suse-openstack-cloud:8"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud Crowbar 8",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud Crowbar 8",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud Crowbar 8",
							"product_id": "SUSE OpenStack Cloud Crowbar 8",
							"cpe": "cpe:/o:suse:suse-openstack-cloud-crowbar:8"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-pip-9.0.1-3.6.1",
				"full_product_name": {
					"text": "python-pip-9.0.1-3.6.1",
					"product_id": "python-pip-9.0.1-3.6.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-pip-9.0.1-3.6.1",
				"full_product_name": {
					"text": "python3-pip-9.0.1-3.6.1",
					"product_id": "python3-pip-9.0.1-3.6.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-pip-9.0.1-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "HPE Helion OpenStack 8"
			},
			{
				"product_reference": "python-pip-9.0.1-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 8"
			},
			{
				"product_reference": "python-pip-9.0.1-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud Crowbar 8"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-3572",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"HPE Helion OpenStack 8:python-pip-9.0.1-3.6.1",
						"SUSE OpenStack Cloud 8:python-pip-9.0.1-3.6.1",
						"SUSE OpenStack Cloud Crowbar 8:python-pip-9.0.1-3.6.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "3.5",
					"vector_v_2": "AV:N/AC:M/Au:S/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "4.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:N/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2021/suse-su-20212441-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-3572.html",
					"description": "CVE-2021-3572"
				},
				{
					"url": "https://bugzilla.suse.com/1186819",
					"description": "SUSE Bug 1186819"
				}
			]
		}
	]
}
