{
	"document_title": "python311-3.11.9-3.1 on GA media",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2024:14082-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-06-28T00:00:00Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-06-28T00:00:00Z",
		"current_release_date": "2024-06-28T00:00:00Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "python311-3.11.9-3.1 on GA media",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "These are all security issues fixed in the python311-3.11.9-3.1 package on the GA media of openSUSE Tumbleweed.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-Tumbleweed-2024-14082",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-0397/",
			"description": "SUSE CVE CVE-2024-0397 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-4032/",
			"description": "SUSE CVE CVE-2024-4032 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python311-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-3.11.9-3.1",
					"product_id": "python311-3.11.9-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-32bit-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-32bit-3.11.9-3.1",
					"product_id": "python311-32bit-3.11.9-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-curses-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-curses-3.11.9-3.1",
					"product_id": "python311-curses-3.11.9-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-dbm-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-dbm-3.11.9-3.1",
					"product_id": "python311-dbm-3.11.9-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-idle-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-idle-3.11.9-3.1",
					"product_id": "python311-idle-3.11.9-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-tk-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-tk-3.11.9-3.1",
					"product_id": "python311-tk-3.11.9-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-x86-64-v3-3.11.9-3.1",
				"full_product_name": {
					"text": "python311-x86-64-v3-3.11.9-3.1",
					"product_id": "python311-x86-64-v3-3.11.9-3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python311-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-32bit-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-curses-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-dbm-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-idle-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-tk-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-x86-64-v3-3.11.9-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "A defect was discovered in the Python \"ssl\" module where there is a memory\nrace condition with the ssl.SSLContext methods \"cert_store_stats()\" and\n\"get_ca_certs()\". The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-0397",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python311-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-32bit-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-curses-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-dbm-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-idle-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-tk-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-x86-64-v3-3.11.9-3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "4.8",
					"vector_v_3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-0397.html",
					"description": "CVE-2024-0397"
				},
				{
					"url": "https://bugzilla.suse.com/1226447",
					"description": "SUSE Bug 1226447"
				}
			]
		},
		{
			"notes": [
				{
					"text": "The \"ipaddress\" module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as \"globally reachable\" or \"private\". This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn't be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-4032",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python311-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-32bit-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-curses-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-dbm-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-idle-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-tk-3.11.9-3.1",
						"openSUSE Tumbleweed:python311-x86-64-v3-3.11.9-3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "3.7",
					"vector_v_3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-4032.html",
					"description": "CVE-2024-4032"
				},
				{
					"url": "https://bugzilla.suse.com/1226448",
					"description": "SUSE Bug 1226448"
				}
			]
		}
	]
}
