{
	"document_title": "Security update for python-Django",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2024:0251-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-08-18T07:32:42Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-08-18T07:32:42Z",
		"current_release_date": "2024-08-18T07:32:42Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Django",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Django fixes the following issues:\n\n- CVE-2023-23969: Potential denial-of-service via Accept-Language headers (boo#1207565)\n- CVE-2024-38875: Potential denial-of-service attack via certain inputs with a very large number of brackets (boo#1227590)\n- CVE-2024-39329: Username enumeration through timing difference for users with unusable passwords (boo#1227593)\n- CVE-2024-39330: Potential directory traversal in django.core.files.storage.Storage.save() (boo#1227594)\n- CVE-2024-39614: Potential denial-of-service through django.utils.translation.get_supported_language-variant()  (boo#1227595)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-2024-251",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OU4KXNSFOQVRSGL2OQCMRA3EFMPZEGEU/",
			"description": "E-Mail link for openSUSE-SU-2024:0251-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1207565",
			"description": "SUSE Bug 1207565"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1227590",
			"description": "SUSE Bug 1227590"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1227593",
			"description": "SUSE Bug 1227593"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1227594",
			"description": "SUSE Bug 1227594"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1227595",
			"description": "SUSE Bug 1227595"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2023-23969/",
			"description": "SUSE CVE CVE-2023-23969 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-38875/",
			"description": "SUSE CVE CVE-2024-38875 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-39329/",
			"description": "SUSE CVE CVE-2024-39329 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-39330/",
			"description": "SUSE CVE CVE-2024-39330 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-39614/",
			"description": "SUSE CVE CVE-2024-39614 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Package Hub 15 SP5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Package Hub 15 SP5",
						"full_product_name": {
							"text": "SUSE Package Hub 15 SP5",
							"product_id": "SUSE Package Hub 15 SP5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.5",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.5",
						"full_product_name": {
							"text": "openSUSE Leap 15.5",
							"product_id": "openSUSE Leap 15.5",
							"cpe": "cpe:/o:opensuse:leap:15.5"
						}
					}
				],
				"full_product_name": {}
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "In Django 3.2 before 3.2.17, 4.0 before 4.0.9, and 4.1 before 4.1.6, the parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if the raw value of Accept-Language headers is very large.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2023-23969",
			"product_statuses": [
				{
					"type": "Fixed"
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OU4KXNSFOQVRSGL2OQCMRA3EFMPZEGEU/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2023-23969.html",
					"description": "CVE-2023-23969"
				},
				{
					"url": "https://bugzilla.suse.com/1207565",
					"description": "SUSE Bug 1207565"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-38875",
			"product_statuses": [
				{
					"type": "Fixed"
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OU4KXNSFOQVRSGL2OQCMRA3EFMPZEGEU/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-38875.html",
					"description": "CVE-2024-38875"
				},
				{
					"url": "https://bugzilla.suse.com/1227590",
					"description": "SUSE Bug 1227590"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-39329",
			"product_statuses": [
				{
					"type": "Fixed"
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "5.3",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OU4KXNSFOQVRSGL2OQCMRA3EFMPZEGEU/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-39329.html",
					"description": "CVE-2024-39329"
				},
				{
					"url": "https://bugzilla.suse.com/1227590",
					"description": "SUSE Bug 1227590"
				},
				{
					"url": "https://bugzilla.suse.com/1227593",
					"description": "SUSE Bug 1227593"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. Derived classes of the django.core.files.storage.Storage base class, when they override generate_filename() without replicating the file-path validations from the parent class, potentially allow directory traversal via certain inputs during a save() call. (Built-in Storage sub-classes are unaffected.)",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-39330",
			"product_statuses": [
				{
					"type": "Fixed"
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OU4KXNSFOQVRSGL2OQCMRA3EFMPZEGEU/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-39330.html",
					"description": "CVE-2024-39330"
				},
				{
					"url": "https://bugzilla.suse.com/1227590",
					"description": "SUSE Bug 1227590"
				},
				{
					"url": "https://bugzilla.suse.com/1227594",
					"description": "SUSE Bug 1227594"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-39614",
			"product_statuses": [
				{
					"type": "Fixed"
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OU4KXNSFOQVRSGL2OQCMRA3EFMPZEGEU/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-39614.html",
					"description": "CVE-2024-39614"
				},
				{
					"url": "https://bugzilla.suse.com/1227590",
					"description": "SUSE Bug 1227590"
				},
				{
					"url": "https://bugzilla.suse.com/1227595",
					"description": "SUSE Bug 1227595"
				}
			]
		}
	]
}
