{
	"document_title": "python310-numpy1-1.26.4-1.1 on GA media",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2024:14311-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-09-04T00:00:00Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-09-04T00:00:00Z",
		"current_release_date": "2024-09-04T00:00:00Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "python310-numpy1-1.26.4-1.1 on GA media",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "These are all security issues fixed in the python310-numpy1-1.26.4-1.1 package on the GA media of openSUSE Tumbleweed.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-Tumbleweed-2024-14311",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2017-12852/",
			"description": "SUSE CVE CVE-2017-12852 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-6446/",
			"description": "SUSE CVE CVE-2019-6446 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-33430/",
			"description": "SUSE CVE CVE-2021-33430 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-41495/",
			"description": "SUSE CVE CVE-2021-41495 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-41496/",
			"description": "SUSE CVE CVE-2021-41496 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python310-numpy1-1.26.4-1.1",
				"full_product_name": {
					"text": "python310-numpy1-1.26.4-1.1",
					"product_id": "python310-numpy1-1.26.4-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python310-numpy1-devel-1.26.4-1.1",
				"full_product_name": {
					"text": "python310-numpy1-devel-1.26.4-1.1",
					"product_id": "python310-numpy1-devel-1.26.4-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-numpy1-1.26.4-1.1",
				"full_product_name": {
					"text": "python311-numpy1-1.26.4-1.1",
					"product_id": "python311-numpy1-1.26.4-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-numpy1-devel-1.26.4-1.1",
				"full_product_name": {
					"text": "python311-numpy1-devel-1.26.4-1.1",
					"product_id": "python311-numpy1-devel-1.26.4-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python312-numpy1-1.26.4-1.1",
				"full_product_name": {
					"text": "python312-numpy1-1.26.4-1.1",
					"product_id": "python312-numpy1-1.26.4-1.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python312-numpy1-devel-1.26.4-1.1",
				"full_product_name": {
					"text": "python312-numpy1-devel-1.26.4-1.1",
					"product_id": "python312-numpy1-devel-1.26.4-1.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python310-numpy1-1.26.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python310-numpy1-devel-1.26.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-numpy1-1.26.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-numpy1-devel-1.26.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python312-numpy1-1.26.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python312-numpy1-devel-1.26.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2017-12852",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python310-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-devel-1.26.4-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.9",
					"vector_v_2": "AV:L/AC:L/Au:N/C:N/I:N/A:C"
				},
				"score_set_v_3": {
					"base_score_v_3": "6.2",
					"vector_v_3": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2017-12852.html",
					"description": "CVE-2017-12852"
				},
				{
					"url": "https://bugzilla.suse.com/1053963",
					"description": "SUSE Bug 1053963"
				}
			]
		},
		{
			"notes": [
				{
					"text": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-6446",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python310-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-devel-1.26.4-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.8",
					"vector_v_3": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-6446.html",
					"description": "CVE-2019-6446"
				},
				{
					"url": "https://bugzilla.suse.com/1122208",
					"description": "SUSE Bug 1122208"
				}
			]
		},
		{
			"notes": [
				{
					"text": "** DISPUTED ** A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-33430",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python310-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-devel-1.26.4-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "3.5",
					"vector_v_2": "AV:N/AC:M/Au:S/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-33430.html",
					"description": "CVE-2021-33430"
				},
				{
					"url": "https://bugzilla.suse.com/1193913",
					"description": "SUSE Bug 1193913"
				},
				{
					"url": "https://bugzilla.suse.com/1201968",
					"description": "SUSE Bug 1201968"
				}
			]
		},
		{
			"notes": [
				{
					"text": "** DISPUTED ** Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-41495",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python310-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-devel-1.26.4-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "3.5",
					"vector_v_2": "AV:N/AC:M/Au:S/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.5",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-41495.html",
					"description": "CVE-2021-41495"
				},
				{
					"url": "https://bugzilla.suse.com/1193911",
					"description": "SUSE Bug 1193911"
				}
			]
		},
		{
			"notes": [
				{
					"text": "** DISPUTED ** Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-41496",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python310-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python311-numpy1-devel-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-1.26.4-1.1",
						"openSUSE Tumbleweed:python312-numpy1-devel-1.26.4-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "2.1",
					"vector_v_2": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.5",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-41496.html",
					"description": "CVE-2021-41496"
				},
				{
					"url": "https://bugzilla.suse.com/1193907",
					"description": "SUSE Bug 1193907"
				}
			]
		}
	]
}
